// Mocks generated by Mockito 5.4.6 from annotations
// in mpx/test/widgets/ingredient_tile_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mpx/models/ingredient.dart' as _i3;
import 'package:mpx/models/product.dart' as _i5;
import 'package:mpx/viewModels/ingredientVM.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IngredientVM].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientVM extends _i1.Mock implements _i2.IngredientVM {
  MockIngredientVM() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Ingredient> get ingredients =>
      (super.noSuchMethod(
            Invocation.getter(#ingredients),
            returnValue: <_i3.Ingredient>[],
          )
          as List<_i3.Ingredient>);

  @override
  bool get loading =>
      (super.noSuchMethod(Invocation.getter(#loading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addIngredient(_i3.Ingredient? ingredient) => super.noSuchMethod(
    Invocation.method(#addIngredient, [ingredient]),
    returnValueForMissingStub: null,
  );

  @override
  void removeIngredient(_i3.Ingredient? ingredient) => super.noSuchMethod(
    Invocation.method(#removeIngredient, [ingredient]),
    returnValueForMissingStub: null,
  );

  @override
  void changeAmount() => super.noSuchMethod(
    Invocation.method(#changeAmount, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i3.Ingredient?> classifyProduct(_i5.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#classifyProduct, [product]),
            returnValue: _i4.Future<_i3.Ingredient?>.value(),
          )
          as _i4.Future<_i3.Ingredient?>);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
