// Mocks generated by Mockito 5.4.6 from annotations
// in mpx/test/services/upc_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:mpx/repositories/spoonacular_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpoonacularRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpoonacularRepository extends _i1.Mock
    implements _i3.SpoonacularRepository {
  MockSpoonacularRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<Map<String, dynamic>> getProductByUPC(String? upc) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByUPC, [upc]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<dynamic>> searchIngredients({
    required String? query,
    int? number = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchIngredients, [], {
              #query: query,
              #number: number,
            }),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<String?> classifyProductCategory({required String? title}) =>
      (super.noSuchMethod(
            Invocation.method(#classifyProductCategory, [], {#title: title}),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<List<dynamic>> getRecipesByIngredients({
    required String? ingredients,
    int? number = 10,
    int? ranking = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipesByIngredients, [], {
              #ingredients: ingredients,
              #number: number,
              #ranking: ranking,
            }),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getIngredientInformation({
    required int? id,
    required double? amount,
    required String? unit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientInformation, [], {
              #id: id,
              #amount: amount,
              #unit: unit,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getRecipeInformation(int? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeInformation, [recipeId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}
