// Mocks generated by Mockito 5.4.6 from annotations
// in mpx/test/viewModels/ingredient_vm_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mpx/models/ingredient.dart' as _i5;
import 'package:mpx/repositories/spoonacular_repository.dart' as _i2;
import 'package:mpx/services/ingredient_service.dart' as _i3;
import 'package:mpx/storage/localStore.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSpoonacularRepository_0 extends _i1.SmartFake
    implements _i2.SpoonacularRepository {
  _FakeSpoonacularRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IngredientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientService extends _i1.Mock implements _i3.IngredientService {
  MockIngredientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SpoonacularRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSpoonacularRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SpoonacularRepository);

  @override
  _i4.Future<List<_i5.Ingredient>> searchIngredients({
    required String? query,
    int? number = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchIngredients, [], {
              #query: query,
              #number: number,
            }),
            returnValue: _i4.Future<List<_i5.Ingredient>>.value(
              <_i5.Ingredient>[],
            ),
          )
          as _i4.Future<List<_i5.Ingredient>>);

  @override
  _i4.Future<_i5.Ingredient?> getIngredientById(int? ingredientId) =>
      (super.noSuchMethod(
            Invocation.method(#getIngredientById, [ingredientId]),
            returnValue: _i4.Future<_i5.Ingredient?>.value(),
          )
          as _i4.Future<_i5.Ingredient?>);
}

/// A class which mocks [LocalStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStore extends _i1.Mock implements _i6.LocalStore {
  MockLocalStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Ingredient>> readIngredients() =>
      (super.noSuchMethod(
            Invocation.method(#readIngredients, []),
            returnValue: _i4.Future<List<_i5.Ingredient>>.value(
              <_i5.Ingredient>[],
            ),
          )
          as _i4.Future<List<_i5.Ingredient>>);

  @override
  _i4.Future<void> writeIngredients(List<_i5.Ingredient>? ingredient) =>
      (super.noSuchMethod(
            Invocation.method(#writeIngredients, [ingredient]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
